services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_strong_password_123
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $$SA_PASSWORD -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 20

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"

  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    ports:
      - "16686:16686"
      - "6831:6831/udp"

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8089:80"
    volumes:
      - seq_data:/data

  apipagos:
    build:
      context: .
      dockerfile: ApiPagos/Dockerfile
    container_name: apipagos
    depends_on:
      - sqlserver
      - rabbit
      - jaeger
      - seq
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Sql=Server=sqlserver,1433;Database=PagosDb;User Id=sa;Password=Your_strong_password_123;TrustServerCertificate=True;
      - RabbitMQ__Host=amqp://guest:guest@rabbit:5672
      - Jaeger__Host=jaeger
      - Jaeger__Port=6831
      - Serilog__WriteTo__0__Name=Console
      - Serilog__WriteTo__1__Name=Seq
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:80
      - Serilog__Enrich__0=FromLogContext
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8082:8080"

  apiconsulta:
    build:
      context: .
      dockerfile: ApiConsulta/Dockerfile
    container_name: apiconsulta
    depends_on:
      - mongo
      - rabbit
      - jaeger
      - seq
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - Mongo__ConnectionString=mongodb://mongo:27017
      - Mongo__Database=ConsultasDb
      - Mongo__Collection=Consultas
      - RabbitMQ__Host=amqp://guest:guest@rabbit:5672
      - Jaeger__Host=jaeger
      - Jaeger__Port=6831
      - Serilog__WriteTo__0__Name=Console
      - Serilog__WriteTo__1__Name=Seq
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:80
      - Serilog__Enrich__0=FromLogContext
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8083:8080"

  apipedidos:
    build:
      context: .
      dockerfile: ApiPedidos/Dockerfile
    container_name: apipedidos
    depends_on:
      - sqlserver
      - rabbit
      - jaeger
      - seq
      - apipagos
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Sql=Server=sqlserver,1433;Database=PedidosDb;User Id=sa;Password=Your_strong_password_123;TrustServerCertificate=True;
      - Apis__PagosBase=http://apipagos:8080
      - RabbitMQ__Host=amqp://guest:guest@rabbit:5672
      - Jaeger__Host=jaeger
      - Jaeger__Port=6831
      - Serilog__WriteTo__0__Name=Console
      - Serilog__WriteTo__1__Name=Seq
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:80
      - Serilog__Enrich__0=FromLogContext
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8081:8080"

volumes:
  mssql_data:
  mongo_data:
  seq_data:
